if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js

node_js:
    - "6.10.2"

jobs:
    include:
        - stage: tests
          name: "Unit Tests"
          script: npm run test-ci
        - stage: github pages deploy
          name: "Build example and deploy to GitHub Pages"
          script: npm run build:example
          deploy:
              provider: pages
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              local_dir: build/
              keep-history: true
              on:
                  branch: master
