if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

language: node_js

node_js:
    - "6.10.2"

jobs:
    include:
        - stage: build
          name: "Build project"
          script: npm run build
        - stage: tests
          name: "Unit Tests"
          script: npm run test-ci

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: build/
    keep-history: true
    on:
        branch: master
