language: node_js

node_js:
    - "6.10.2"

jobs:
    include:
        - stage: tests
          name: "Unit Tests"
          script: npm run test-ci
        - stage: deploy
          name: "Deploy to GitHub Pages"
          script: rnm run deploy
          if: branch = master
